### ISSUE TITLE
Building MongoDB::Atlas::DatabaseUser and MongoDB::Atlas::EncryptionAtRest fails

### ISSUE THREAD

**Issue by azec-pdx** [mongodb/mongodbatlas-cloudformation-resources#21]
Environment:

```
> pip show cloudformation-cli

Name: cloudformation-cli
Version: 0.1.3
Summary: UNKNOWN
Home-page: https://github.com/aws-cloudformation/aws-cloudformation-rpdk/
Author: Amazon Web Services
Author-email: aws-cloudformation-developers@amazon.com
License: Apache License 2.0
Location: /Users/azec/.pyenv/versions/3.7.4/lib/python3.7/site-packages
Requires: jsonschema, Werkzeug, colorama, requests, hypothesis, pytest, PyYAML, boto3, Jinja2
Required-by: cloudformation-cli-go-plugin
```
and ...
```
pip show cloudformation-cli-go-plugin

Name: cloudformation-cli-go-plugin
Version: 0.1.2
Summary: UNKNOWN
Home-page: https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/
Author: Amazon Web Services
Author-email: aws-cloudformation-developers@amazon.com
License: Apache License 2.0
Location: /Users/azec/.pyenv/versions/3.7.4/lib/python3.7/site-packages
Requires: cloudformation-cli
Required-by: 
```

## Error for `MongoDB::Atlas::EncryptionAtRest`
When building `MongoDB::Atlas::EncryptionAtRest` with `make`: 

```
>    make

cfn generate
resource/model.go
main.go
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: https://github.com/aws-cloudformation/aws-cloudformation-rpdk/issues
Please include the log file 'rpdk.log'
make: *** [build] Error 127
```

Content of `rpdk.log`:
```
[2020-05-14T21:13:54Z] DEBUG    - Logging set up successfully
[2020-05-14T21:13:54Z] DEBUG    - Running generate: Namespace(command=<function generate at 0x10dd3cf80>, subparser_name='generate', verbose=0, version=False)
[2020-05-14T21:13:54Z] DEBUG    - Root directory: /Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/encryption-at-rest
[2020-05-14T21:13:54Z] DEBUG    - Loading project file '/Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/encryption-at-rest/.rpdk-config'
[2020-05-14T21:13:54Z] INFO     - Validating your resource specification...
[2020-05-14T21:13:54Z] DEBUG    - Resolved '#/definitions/AwsKms' to 'file:///Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/encryption-at-rest/mongodb-atlas-encryptionatrest.json#/definitions/AwsKms'
[2020-05-14T21:13:54Z] DEBUG    - Parsed 'file:///Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/encryption-at-rest/mongodb-atlas-encryptionatrest.json#/definitions/AwsKms' to '(<BASE>, 'definitions', 'AwsKms')'
[2020-05-14T21:13:54Z] DEBUG    - Edge from '(<BASE>, 'properties', 'AwsKms')' to '(<BASE>, 'definitions', 'AwsKms')'
[2020-05-14T21:13:54Z] DEBUG    - Resolved '#/definitions/apiKeyDefinition' to 'file:///Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/encryption-at-rest/mongodb-atlas-encryptionatrest.json#/definitions/apiKeyDefinition'
[2020-05-14T21:13:54Z] DEBUG    - Parsed 'file:///Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/encryption-at-rest/mongodb-atlas-encryptionatrest.json#/definitions/apiKeyDefinition' to '(<BASE>, 'definitions', 'apiKeyDefinition')'
[2020-05-14T21:13:54Z] DEBUG    - Edge from '(<BASE>, 'properties', 'ApiKeys')' to '(<BASE>, 'definitions', 'apiKeyDefinition')'
[2020-05-14T21:13:54Z] DEBUG    - Rewriting refs in '<BASE>' (file:///Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/encryption-at-rest/mongodb-atlas-encryptionatrest.json)
[2020-05-14T21:13:54Z] DEBUG    -   '#/definitions/AwsKms' -> '#/definitions/AwsKms'
[2020-05-14T21:13:54Z] DEBUG    -   '#/definitions/apiKeyDefinition' -> '#/definitions/apiKeyDefinition'
[2020-05-14T21:13:54Z] DEBUG    - Writing Resource Role CloudFormation template: /Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/encryption-at-rest/resource-role.yaml
[2020-05-14T21:13:54Z] DEBUG    - Overwriting '/Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/encryption-at-rest/resource-role.yaml'
[2020-05-14T21:13:54Z] DEBUG    - Generate started
[2020-05-14T21:13:54Z] DEBUG    - Writing Types
[2020-05-14T21:13:54Z] DEBUG    - Overwriting '/Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/encryption-at-rest/cmd/resource/model.go'
[2020-05-14T21:13:54Z] DEBUG    - Writing project: /Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/encryption-at-rest/cmd/main.go
[2020-05-14T21:13:54Z] DEBUG    - Overwriting '/Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/encryption-at-rest/cmd/main.go'
[2020-05-14T21:13:55Z] DEBUG    - Removing generated docs: /Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/encryption-at-rest/docs
[2020-05-14T21:13:55Z] DEBUG    - Writing generated docs
[2020-05-14T21:13:55Z] DEBUG    - Writing docs awskms.md: /Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/encryption-at-rest/docs/awskms.md
[2020-05-14T21:13:55Z] DEBUG    - Writing docs apikeys.md: /Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/encryption-at-rest/docs/apikeys.md
[2020-05-14T21:13:55Z] DEBUG    - Finished documenting nested properties
[2020-05-14T21:13:55Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/Users/azec/.pyenv/versions/3.7.4/lib/python3.7/site-packages/rpdk/core/cli.py", line 98, in main
    args.command(args)
  File "/Users/azec/.pyenv/versions/3.7.4/lib/python3.7/site-packages/rpdk/core/generate.py", line 16, in generate
    project.generate_docs()
  File "/Users/azec/.pyenv/versions/3.7.4/lib/python3.7/site-packages/rpdk/core/project.py", line 373, in generate_docs
    getatt = self._get_docs_gettable_atts(docs_schema)
  File "/Users/azec/.pyenv/versions/3.7.4/lib/python3.7/site-packages/rpdk/core/project.py", line 413, in _get_docs_gettable_atts
    for prop in docs_schema.get("readOnlyProperties", [])
  File "/Users/azec/.pyenv/versions/3.7.4/lib/python3.7/site-packages/rpdk/core/project.py", line 413, in <listcomp>
    for prop in docs_schema.get("readOnlyProperties", [])
  File "/Users/azec/.pyenv/versions/3.7.4/lib/python3.7/site-packages/rpdk/core/project.py", line 402, in _get_property_description
    name = path[-1]
IndexError: tuple index out of range
```

## Error for `MongoDB::Atlas::DatabaseUser`
When building `MongoDB::Atlas::DatabaseUser` with `make`: 

```
>    make

cfn generate
resource/model.go
main.go
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: https://github.com/aws-cloudformation/aws-cloudformation-rpdk/issues
Please include the log file 'rpdk.log'
make: *** [build] Error 127
```

Content of `rpdk.log`:

```
[2020-05-14T21:22:23Z] DEBUG    - Logging set up successfully
[2020-05-14T21:22:23Z] DEBUG    - Running generate: Namespace(command=<function generate at 0x101c3cf80>, subparser_name='generate', verbose=0, version=False)
[2020-05-14T21:22:23Z] DEBUG    - Root directory: /Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/database-user
[2020-05-14T21:22:23Z] DEBUG    - Loading project file '/Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/database-user/.rpdk-config'
[2020-05-14T21:22:23Z] INFO     - Validating your resource specification...
[2020-05-14T21:22:23Z] DEBUG    - Resolved '#/definitions/labelDefinition' to 'file:///Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/database-user/mongodb-atlas-databaseuser.json#/definitions/labelDefinition'
[2020-05-14T21:22:23Z] DEBUG    - Parsed 'file:///Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/database-user/mongodb-atlas-databaseuser.json#/definitions/labelDefinition' to '(<BASE>, 'definitions', 'labelDefinition')'
[2020-05-14T21:22:23Z] DEBUG    - Edge from '(<BASE>, 'properties', 'Labels', 'items')' to '(<BASE>, 'definitions', 'labelDefinition')'
[2020-05-14T21:22:23Z] DEBUG    - Resolved '#/definitions/roleDefinition' to 'file:///Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/database-user/mongodb-atlas-databaseuser.json#/definitions/roleDefinition'
[2020-05-14T21:22:23Z] DEBUG    - Parsed 'file:///Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/database-user/mongodb-atlas-databaseuser.json#/definitions/roleDefinition' to '(<BASE>, 'definitions', 'roleDefinition')'
[2020-05-14T21:22:23Z] DEBUG    - Edge from '(<BASE>, 'properties', 'Roles', 'items')' to '(<BASE>, 'definitions', 'roleDefinition')'
[2020-05-14T21:22:23Z] DEBUG    - Resolved '#/definitions/apiKeyDefinition' to 'file:///Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/database-user/mongodb-atlas-databaseuser.json#/definitions/apiKeyDefinition'
[2020-05-14T21:22:23Z] DEBUG    - Parsed 'file:///Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/database-user/mongodb-atlas-databaseuser.json#/definitions/apiKeyDefinition' to '(<BASE>, 'definitions', 'apiKeyDefinition')'
[2020-05-14T21:22:23Z] DEBUG    - Edge from '(<BASE>, 'properties', 'ApiKeys')' to '(<BASE>, 'definitions', 'apiKeyDefinition')'
[2020-05-14T21:22:23Z] DEBUG    - Rewriting refs in '<BASE>' (file:///Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/database-user/mongodb-atlas-databaseuser.json)
[2020-05-14T21:22:23Z] DEBUG    -   '#/definitions/labelDefinition' -> '#/definitions/labelDefinition'
[2020-05-14T21:22:23Z] DEBUG    -   '#/definitions/roleDefinition' -> '#/definitions/roleDefinition'
[2020-05-14T21:22:23Z] DEBUG    -   '#/definitions/apiKeyDefinition' -> '#/definitions/apiKeyDefinition'
[2020-05-14T21:22:23Z] DEBUG    - Writing Resource Role CloudFormation template: /Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/database-user/resource-role.yaml
[2020-05-14T21:22:23Z] DEBUG    - Overwriting '/Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/database-user/resource-role.yaml'
[2020-05-14T21:22:23Z] DEBUG    - Generate started
[2020-05-14T21:22:23Z] DEBUG    - Writing Typesi
[2020-05-14T21:22:23Z] DEBUG    - Overwriting '/Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/database-user/cmd/resource/model.go'
[2020-05-14T21:22:23Z] DEBUG    - Writing project: /Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/database-user/cmd/main.go
[2020-05-14T21:22:23Z] DEBUG    - Overwriting '/Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/database-user/cmd/main.go'
[2020-05-14T21:22:23Z] DEBUG    - Removing generated docs: /Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/database-user/docs
[2020-05-14T21:22:23Z] DEBUG    - Writing generated docs
[2020-05-14T21:22:23Z] DEBUG    - Writing docs labels.md: /Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/database-user/docs/labels.md
[2020-05-14T21:22:23Z] DEBUG    - Writing docs roles.md: /Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/database-user/docs/roles.md
[2020-05-14T21:22:23Z] DEBUG    - Writing docs apikeys.md: /Users/azec/dev/go-workspace/src/mongodbatlas-cloudformation-resources-v013/database-user/docs/apikeys.md
[2020-05-14T21:22:23Z] DEBUG    - Finished documenting nested properties
[2020-05-14T21:22:23Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/Users/azec/.pyenv/versions/3.7.4/lib/python3.7/site-packages/rpdk/core/cli.py", line 98, in main
    args.command(args)
  File "/Users/azec/.pyenv/versions/3.7.4/lib/python3.7/site-packages/rpdk/core/generate.py", line 16, in generate
    project.generate_docs()
  File "/Users/azec/.pyenv/versions/3.7.4/lib/python3.7/site-packages/rpdk/core/project.py", line 373, in generate_docs
    getatt = self._get_docs_gettable_atts(docs_schema)
  File "/Users/azec/.pyenv/versions/3.7.4/lib/python3.7/site-packages/rpdk/core/project.py", line 413, in _get_docs_gettable_atts
    for prop in docs_schema.get("readOnlyProperties", [])
  File "/Users/azec/.pyenv/versions/3.7.4/lib/python3.7/site-packages/rpdk/core/project.py", line 413, in <listcomp>
    for prop in docs_schema.get("readOnlyProperties", [])
  File "/Users/azec/.pyenv/versions/3.7.4/lib/python3.7/site-packages/rpdk/core/project.py", line 402, in _get_property_description
    name = path[-1]
IndexError: tuple index out of range

```

`SUMMARY:` In both instances , issue is presence of empty `readOnlyProperties` array in JSON resource definition schema. When removed , build passes fine for both resources. 
```
"readOnlyProperties": [
        ""
    ],
```

Problematic lines:
1. `MongoDB::Atlas::EncryptionAtRest` : https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/encryption-at-rest/mongodb-atlas-encryptionatrest.json#L63
2. `MongoDB::Atlas::DatabaseUser` : https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/database-user/mongodb-atlas-databaseuser.json#L103-L105

**Comment by themantissa** [comment]
@thetonymaster  please take a look

Also @azec-pdx we have provided a release in the repo to make this, hopefully, smoother.
