### ISSUE TITLE
Reference vpc peering connectionId not working

### ISSUE THREAD

**Issue by matsekroth** [mongodb/mongodbatlas-cloudformation-resources#213]
I am trying to attach a route table to my VPC peering connection in the same template as where I setup the VPC peering and it doesn't allow me to read the property from the NetworkPeering object.

### CloudFormation Template 
These are the relevant parts from my CloudFormation template.

```
"DatabricksNetworkPeering": {
   "Type": "MongoDB::Atlas::NetworkPeering",
   "Properties": {
    "ApiKeys": {
     "PublicKey": {
      "Ref": "importedmongodbatlaspublickeyParameter"
     },
     "PrivateKey": {
      "Ref": "importedmongodbatlasprivatekeyParameter"
     }
    },
    "ProjectId": {
     "Ref": "AtlasProject"
    },
    "ContainerId": {
     "Ref": "AtlasNetworkContainer"
    },
    "AccepterRegionName": {
     "Ref": "AWS::Region"
    },
    "AwsAccountId": {
     "Ref": "AWS::AccountId"
    },
    "RouteTableCIDRBlock": {
     "Fn::ImportValue": "databricks-vpc-CidrBlock"
    },
    "VpcId": {
     "Fn::ImportValue": "databricks-vpc-VpcId"
    }
   }
  },
"RouteFromPrivateSubnetOfDatabricksToMongoDBOne": {
   "Type": "AWS::EC2::Route",
   "Properties": {
    "RouteTableId": {
     "Fn::ImportValue": "databricks-network-PrivateSubnetOneRouteTableId"
    },
    "DestinationCidrBlock": {
      "Ref": "monogdbCidrBlock"
     },
    "VpcPeeringConnectionId": {
     "Fn::GetAtt": [
      "DatabricksNetworkPeering",
      "ConnectionId"
     ]
    }
   },
   "DependsOn": [
    "DatabricksNetworkPeering"
   ]
  }
```

### Steps to Reproduce
Create a VPC peering and a EC2 Route in the same template and try to get the connectionId from the network peering.

### Expected Behavior
An id that starts with "pcx-" should be returned from the GetAtt ConnectionId

### Actual Behavior
Getting this issue:
```
15:09:09 | CREATE_FAILED        | AWS::EC2::Route                     | dev/RouteFromPrivateSubnetOfDatabricksToMongoDBOne (RouteFromPrivateSubnetOfDatabricksToMongoDBOne) Requested attribute ConnectionId must be a readonly property in schema for MongoDB::Atlas::NetworkPeering       

 ❌  dev (hfs2-dev-mongo-db-atlas) failed: Error: The stack named hfs2-dev-mongo-db-atlas failed to deploy: UPDATE_ROLLBACK_COMPLETE: Requested attribute ConnectionId must be a readonly property in schema for MongoDB::Atlas::NetworkPeering, Requested attribute ConnectionId must be a readonly property in schema for MongoDB::Atlas::NetworkPeering    at FullCloudFormationDeployment.monitorDeployment (C:\Users\matsp\AppData\Roaming\nvm\v16.17.1\node_modules\aws-cdk\lib\api\deploy-stack.ts:505:13)    
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at deployStack2 (C:\Users\matsp\AppData\Roaming\nvm\v16.17.1\node_modules\aws-cdk\lib\cdk-toolkit.ts:265:24)
    at C:\Users\matsp\AppData\Roaming\nvm\v16.17.1\node_modules\aws-cdk\lib\deploy.ts:39:11
    at run (C:\Users\matsp\AppData\Roaming\nvm\v16.17.1\node_modules\p-queue\dist\index.js:163:29)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named hfs2-dev-mongo-db-atlas failed to deploy: UPDATE_ROLLBACK_COMPLETE: Requested attribute ConnectionId must be a readonly property in schema for MongoDB::Atlas::NetworkPeering, Requested attribute ConnectionId must be a readonly property in schema for MongoDB::Atlas::NetworkPeering    at deployStacks (C:\Users\matsp\AppData\Roaming\nvm\v16.17.1\node_modules\aws-cdk\lib\deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (C:\Users\matsp\AppData\Roaming\nvm\v16.17.1\node_modules\aws-cdk\lib\cdk-toolkit.ts:339:7)
    at exec4 (C:\Users\matsp\AppData\Roaming\nvm\v16.17.1\node_modules\aws-cdk\lib\cli.ts:384:12)

Stack Deployments Failed: Error: The stack named hfs2-dev-mongo-db-atlas failed to deploy: UPDATE_ROLLBACK_COMPLETE: Requested attribute ConnectionId must be a readonly property in schema for MongoDB::Atlas::NetworkPeering, Requested attribute ConnectionId must be a readonly property in schema for MongoDB::Atlas::NetworkPeering
```

**Comment by Zuhairahmed** [comment]
Hi @matsekroth just as a quick update, we are still working through this issue and should have an update for in next 1-2 weeks.

**Comment by matsekroth** [comment]
Thanks for the update, looking forward to the next update 👍

**Comment by Zuhairahmed** [comment]
@matsekroth can you retest? we have finished publishing update to this CDK resource. note you have to store MongoDB API access key credentials via AWS Secrets Management now, see details here: https://github.com/mongodb/mongodbatlas-cloudformation-resources#mongodb-atlas-api-keys-credential-management

**Comment by Zuhairahmed** [comment]
closing issue since issues appears to have ben resolved, feel free to open a new issue if you need anything else
