### ISSUE TITLE
IP not allowed in ProjectIpAccessList

### ISSUE THREAD

**Issue by matsekroth** [mongodb/mongodbatlas-cloudformation-resources#214]
I have tried to setup a IP access list in cloudformation to allow IPs from our office and other places by default. I have also tried to add the CIDR-blocks from out VPC peering into the same resource which works, but when I add the IP:s it doesn't work.

### CloudFormation Template 
```
"AtlasIpAccessList": {
   "Type": "MongoDB::Atlas::ProjectIpAccessList",
   "Properties": {
    "ProjectId": {
     "Ref": "AtlasProject"
    },
    "ApiKeys": {
     "PublicKey": {
      "Ref": "importedmongodbatlaspublickeyParameter"
     },
     "PrivateKey": {
      "Ref": "importedmongodbatlasprivatekeyParameter"
     }
    },
    "AccessList": [
     {
      "Comment": "Office IP 1 ",
      "IPAddress": "xxx.xxx.xxx.xxx/23"
     },
     {
      "Comment": "Office IP 2 ",
      "IPAddress": "yyy.yyy.yyy.yyy/23"
     },
     {
      "CIDRBlock": {
       "Fn::ImportValue": "hfs2-dev-vpc-CidrBlock"
      },
      "Comment": "Fleet VPC "
     },
     {
      "CIDRBlock": {
       "Fn::ImportValue": "databricks-vpc-CidrBlock"
      },
      "Comment": "Fleet Databricks VPC"
     }
    ]
   },
   "DependsOn": [
    "DatabricksNetworkPeering",
    "FleetNetworkPeering"
   ]
  }
```

### Steps to Reproduce
Try adding an IP into the ProjectIpAccessList resource.

### Expected Behavior
The IP should be added alongside the cidr blocks into the projects whitelisting in Atlas.

### Actual Behavior
Getting the following error:
```
21:44:52 | UPDATE_FAILED        | MongoDB::Atlas::ProjectIpAccessList | dev/AtlasIpAccessList (AtlasIpAccessList) Resource handler returned message: "Error getting resource : DELETE https://cloud.mongodb.com/api/atlas/v1.0/groups/63d454d5bcf2a040f70f7bae/accessList/xxx.xxx.xxx.xxx%2F23: 404 (request "ATLAS_NETWORK_PERMISSION_ENTRY_NOT_FOUND") IP Address xxx.xxx.xxx.xxx/23 not on Atlas access list for group 63d454d5bcf2a040f70f7bae." (RequestToken: 1e5219b8-24fe-8c0b-58d1-b2fff9fe1788, HandlerErrorCode: NotFound)
 ❌  dev (hfs2-dev-mongo-db-atlas) failed: Error: The stack named hfs2-dev-mongo-db-atlas failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "Error getting resource : DELETE https://cloud.mongodb.com/api/atlas/v1.0/groups/63d454d5bcf2a040f70f7bae/accessList/xxx.xxx.xxx.xxx%2F23: 404 (request "ATLAS_NETWORK_PERMISSION_ENTRY_NOT_FOUND") IP Address xxx.xxx.xxx.xxx/23 not on Atlas access list for group 63d454d5bcf2a040f70f7bae." (RequestToken: 1e5219b8-24fe-8c0b-58d1-b2fff9fe1788, HandlerErrorCode: NotFound)
    at FullCloudFormationDeployment.monitorDeployment (C:\Users\matsp\AppData\Roaming\nvm\v16.17.1\node_modules\aws-cdk\lib\api\deploy-stack.ts:505:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at deployStack2 (C:\Users\matsp\AppData\Roaming\nvm\v16.17.1\node_modules\aws-cdk\lib\cdk-toolkit.ts:265:24)
    at C:\Users\matsp\AppData\Roaming\nvm\v16.17.1\node_modules\aws-cdk\lib\deploy.ts:39:11
    at run (C:\Users\matsp\AppData\Roaming\nvm\v16.17.1\node_modules\p-queue\dist\index.js:163:29)
 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named hfs2-dev-mongo-db-atlas failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "Error getting resource : DELETE https://cloud.mongodb.com/api/atlas/v1.0/groups/63d454d5bcf2a040f70f7bae/accessList/xxx.xxx.xxx.xxx%2F23: 404 (request "ATLAS_NETWORK_PERMISSION_ENTRY_NOT_FOUND") IP Address xxx.xxx.xxx.xxx/23 not on Atlas access list for group 63d454d5bcf2a040f70f7bae." (RequestToken: 1e5219b8-24fe-8c0b-58d1-b2fff9fe1788, HandlerErrorCode: NotFound)      
    at deployStacks (C:\Users\matsp\AppData\Roaming\nvm\v16.17.1\node_modules\aws-cdk\lib\deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (C:\Users\matsp\AppData\Roaming\nvm\v16.17.1\node_modules\aws-cdk\lib\cdk-toolkit.ts:339:7)
    at exec4 (C:\Users\matsp\AppData\Roaming\nvm\v16.17.1\node_modules\aws-cdk\lib\cli.ts:384:12)
Stack Deployments Failed: Error: The stack named hfs2-dev-mongo-db-atlas failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "Error getting resource : DELETE https://cloud.mongodb.com/api/atlas/v1.0/groups/63d454d5bcf2a040f70f7bae/accessList/xxx.xxx.xxx.xxx%2F23: 404 (request "ATLAS_NETWORK_PERMISSION_ENTRY_NOT_FOUND") IP Address xxx.xxx.xxx.xxx/23 not on Atlas access list for group 63d454d5bcf2a040f70f7bae." (RequestToken: 1e5219b8-24fe-8c0b-58d1-b2fff9fe1788, HandlerErrorCode: NotFound)
```

### Additional Context
I am using CDK but manually creating the objects as CfnResource classes. My examples are from the cdk synth output since that is what will be uploaded to AWS which is the relevant part. I have tried to remove the cdk specific stuff from the template to keep it clean for the issue but there are some cdk references in the error log, but that should not be relevant for this issue as long as the output from cdk synth is correct.

**Comment by Zuhairahmed** [comment]
Hi @matsekroth we are still working through this issue and should have an update to share in the next 1-2 weeks.

**Comment by matsekroth** [comment]
Thanks for the update, looking forward to the next update 👍

**Comment by Adelmar92** [comment]
Hi @matsekroth we made some changes on this resource, you might want to use the new version (1.3.0) note that in this new version the API keys need to be provided by the concept of PROFILE, configured with AWS Secret Manager, please check this [guide](https://github.com/mongodb/mongodbatlas-cloudformation-resources#mongodb-atlas-api-keys-credential-management) to set up the AWS profile with Secret Manager

**Comment by Zuhairahmed** [comment]
closing issue since issues appears to have ben resolved, feel free to open a new issue if you need anything else
