### ISSUE TITLE
empty readOnlyProperties in database user schema causes error

### ISSUE THREAD

**Issue by jasonmimick** [mongodb/mongodbatlas-cloudformation-resources#24]
Got error trying to build the database user resource.

```
[2020-06-01T19:07:07Z] DEBUG    - Writing Makefile: /home/jason/work/mongodbatlas-cloudformation-resources/database-user/Make
file
[2020-06-01T19:07:07Z] DEBUG    - Overwriting '/home/jason/work/mongodbatlas-cloudformation-resources/database-user/Makefile'
[2020-06-01T19:07:07Z] DEBUG    - Removing generated docs: /home/jason/work/mongodbatlas-cloudformation-resources/database-us
er/docs
[2020-06-01T19:07:07Z] DEBUG    - Writing generated docs
[2020-06-01T19:07:07Z] DEBUG    - Writing docs labels.md: /home/jason/work/mongodbatlas-cloudformation-resources/database-use
r/docs/labels.md
[2020-06-01T19:07:07Z] DEBUG    - Writing docs roles.md: /home/jason/work/mongodbatlas-cloudformation-resources/database-user
/docs/roles.md
[2020-06-01T19:07:07Z] DEBUG    - Writing docs apikeys.md: /home/jason/work/mongodbatlas-cloudformation-resources/database-us
er/docs/apikeys.md
[2020-06-01T19:07:07Z] DEBUG    - Finished documenting nested properties
[2020-06-01T19:07:07Z] WARNING  - prop=
[2020-06-01T19:07:07Z] WARNING  - path=()
[2020-06-01T19:07:07Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/home/jason/.local/lib/python3.7/site-packages/rpdk/core/cli.py", line 98, in main
    args.command(args)
  File "/home/jason/.local/lib/python3.7/site-packages/rpdk/core/generate.py", line 16, in generate
    project.generate_docs()
  File "/home/jason/.local/lib/python3.7/site-packages/rpdk/core/project.py", line 373, in generate_docs
    getatt = self._get_docs_gettable_atts(docs_schema)
  File "/home/jason/.local/lib/python3.7/site-packages/rpdk/core/project.py", line 415, in _get_docs_gettable_atts
    for prop in docs_schema.get("readOnlyProperties", [])
  File "/home/jason/.local/lib/python3.7/site-packages/rpdk/core/project.py", line 415, in <listcomp>
    for prop in docs_schema.get("readOnlyProperties", [])
  File "/home/jason/.local/lib/python3.7/site-packages/rpdk/core/project.py", line 404, in _get_property_description
    name = path[-1]
IndexError: tuple index out of range
```

I was able to fix this by adding
```
   "readOnlyProperties": [
        "/properties/DatabaseName",
        "/properties/ProjectId",
        "/properties/Username"
    ],
```
to the database user schema seems to fix.
See https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/fe5eb3aa81ca49bce31695f55a2abd3cdd2d220f/database-user/mongodb-atlas-databaseuser.json#L104

Thanks-

**Comment by jasonmimick** [comment]
Duplicate of #21
