### ISSUE TITLE
MongoDB Atlast CDK deploy fails with message "internal error".

### ISSUE THREAD

**Issue by matt-github-acct** [mongodb/mongodbatlas-cloudformation-resources#93]
### CloudFormation Template 
```
https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/master/cfn-resources/cluster/docs
```

### Steps to Reproduce
Deploy a cdk stack with the following configuration:

```
import { Construct } from 'constructs';
import { 
    aws_cloudformation as cloudformation,
    CfnResource,
    aws_logs as logs,
    CfnTypeActivation
} from 'aws-cdk-lib';

export class Mongo extends Construct {
    constructor(scope: Construct, id: string) {
        super(scope, id);

        const directorRoleArn = "redacted"
        const mongoLogGroup = new logs.LogGroup(this, "mongo_matterbeam_log_group");

        const activateMongoClusterExtension = new cloudformation.CfnTypeActivation(this, `${id}-Cluster`, {
            publicTypeArn: "arn:aws:cloudformation:us-east-1::type/resource/bb989456c78c398a858fef18f2ca1bfc1fbba082/MongoDB-Atlas-Cluster",
            executionRoleArn: "redacted",
            loggingConfig: {
                logGroupName: mongoLogGroup.logGroupName,
                logRoleArn: directorRoleArn 
            }
        });

        const activateMongoDatabaseUserExtension = new cloudformation.CfnTypeActivation(this, `${id}-DatabaseUser`, {
            publicTypeArn: "arn:aws:cloudformation:us-east-1::type/resource/bb989456c78c398a858fef18f2ca1bfc1fbba082/MongoDB-Atlas-DatabaseUser",
            executionRoleArn: "redacted",
            loggingConfig: {
                logGroupName: mongoLogGroup.logGroupName,
                logRoleArn: directorRoleArn 
            }
        });

        const activateMongoNetworkPeeringExtension = new cloudformation.CfnTypeActivation(this, `${id}-NetworkPeering`, {
            publicTypeArn: "arn:aws:cloudformation:us-east-1::type/resource/bb989456c78c398a858fef18f2ca1bfc1fbba082/MongoDB-Atlas-NetworkPeering",
            executionRoleArn: "redacted",
            loggingConfig: {
                logGroupName: mongoLogGroup.logGroupName,
                logRoleArn: directorRoleArn 
            }
        });

        const activateMongoProjectExtension = new cloudformation.CfnTypeActivation(this, `${id}-Project`, {
            publicTypeArn: "arn:aws:cloudformation:us-east-1::type/resource/bb989456c78c398a858fef18f2ca1bfc1fbba082/MongoDB-Atlas-Project",
            executionRoleArn: "redacted",
            loggingConfig: {
                logGroupName: mongoLogGroup.logGroupName,
                logRoleArn: directorRoleArn 
            }
        });

        const activateMongoAwsIamDatabaseUserExtension = new cloudformation.CfnTypeActivation(this, `${id}-AwsIamDatabaseUser`, {
            publicTypeArn: "arn:aws:cloudformation:us-east-1::type/resource/9331cf547939e23b9c7f24086db031317893be87/MongoDb-Atlas-AwsIamDatabaseUser",
            executionRoleArn: "redacted",
            loggingConfig: {
                logGroupName: mongoLogGroup.logGroupName,
                logRoleArn: directorRoleArn 
            }
        });

        const mongo = new CfnResource(this, "mongo_matterbeam", {
            type: "MongoDB::Atlas::Cluster",
            properties: {
                Name: "mongo_matterbeam"
            }
        });
    }
}
```

### Expected Behavior
A MongoDB Atlas cluster should be deployed to my aws stack.

### Actual Behavior
The command `cdk deploy -v` fails due to an `Internal Failure`.

Here is the full debug log:

```
CustomerStack | 0/3 | 4:34:15 PM | UPDATE_IN_PROGRESS   | AWS::CloudFormation::Stack                  | CustomerStack User Initiated
CustomerStack | 0/3 | 4:34:24 PM | CREATE_IN_PROGRESS   | MongoDB::Atlas::Cluster                     | MongoMatterbeam/mongo_matterbeam (MongoMatterbeammongomatterbeam4673F23D) 

CustomerStack | 0/3 | 5:10:32 PM | CREATE_FAILED        | MongoDB::Atlas::Cluster                     | MongoMatterbeam/mongo_matterbeam (MongoMatterbeammongomatterbeam4673F23D) Internal Failure
CustomerStack | 0/3 | 5:10:35 PM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack                  | CustomerStack Internal Failure
CustomerStack | 1/3 | 5:10:43 PM | UPDATE_ROLLBACK_COMP | AWS::CloudFormation::Stack                  | CustomerStack 
CustomerStack | 2/3 | 5:13:09 PM | DELETE_COMPLETE      | MongoDB::Atlas::Cluster                     | MongoMatterbeam/mongo_matterbeam (MongoMatterbeammongomatterbeam4673F23D) 
CustomerStack | 3/3 | 5:13:09 PM | UPDATE_ROLLBACK_COMP | AWS::CloudFormation::Stack                  | CustomerStack 

Failed resources:
CustomerStack | 5:10:32 PM | CREATE_FAILED        | MongoDB::Atlas::Cluster                     | MongoMatterbeam/mongo_matterbeam (MongoMatterbeammongomatterbeam4673F23D) Internal Failure

 ❌  CustomerStack failed: Error: The stack named CustomerStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Internal Failure
    at prepareAndExecuteChangeSet (/opt/node-v14.17.6-linux-x64/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:385:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at CdkToolkit.deploy (/opt/node-v14.17.6-linux-x64/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:209:24)
    at initCommandLine (/opt/node-v14.17.6-linux-x64/lib/node_modules/aws-cdk/lib/cli.ts:341:12)
Notices refreshed

The stack named CustomerStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Internal Failure
Error: The stack named CustomerStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Internal Failure
    at prepareAndExecuteChangeSet (/opt/node-v14.17.6-linux-x64/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:385:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at CdkToolkit.deploy (/opt/node-v14.17.6-linux-x64/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:209:24)
    at initCommandLine (/opt/node-v14.17.6-linux-x64/lib/node_modules/aws-cdk/lib/cli.ts:341:12)
```

**Comment by mattcbaker** [comment]
Does anyone know how to get more information about the error that's occurring?

**Comment by mattcbaker** [comment]
Closed, I no longer need this. Thank you.

**Comment by mattcbaker** [comment]
Opening this again because I think I might need it after all.

**Comment by ajotaos** [comment]
I have a similar issue to this one.

I used the `MongoDB::Atlas::Project` as part of a CDK stack to create a project and deploy it. It remains, approximately, an hour in `CREATE_IN_PROGRESS` before it reports as `Internal Failure` in the CF events. I double checked on my MongoDB Atlas dashboard and the project wasn't created, nor did it appear as attempted to do it in the ActivityFeed tab.

I used the same parameters (name, organization id and api keys) via curl and it worked on the CLI.

**Comment by ajotaos** [comment]
Are there any updates about this error? @jasonmimick

**Comment by Zuhairahmed** [comment]
@matt-github-acct / @ajotaos we are making several updates to MongoDB::Atlas::Project and other resources which are likely to be released over the next few weeks. Happy to alert this thread when publicly available and you can then let us know if you are still experiencing this issue. Thank you.

**Comment by Zuhairahmed** [comment]
hi @matt-github-acct @ajotaos we have refreshed our resource and published to AWS CFN Third Party Public Registry in all 22 AWS regions where MongoDB Atlas is currently available in. Can you double check now if this has resolved your issue?

**Comment by Zuhairahmed** [comment]
Closing issue, but feel free to re-open in case if you need anything else here

**Comment by areizas** [comment]
Hi @Zuhairahmed, We are having the same `Internal Failure` issue when trying to deploy the quickstart stack via CloudFormation. The Stack gets stuck in UPDATE_IN_PROGRESS for MongoDB::Atlas::Project for 1 hour. Then the stack fails. While it is stuck we noticed that the project is not getting created in our Atlas organization. This was working very well 2 weeks ago.
